SELECT * FROM sales 
LIMIT 10;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue FROM sales
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id FROM sales
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM sales);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC), 1) AS avg_ratings FROM sales
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount FROM sales
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY 1;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount), 2) AS average_spent,
	ROUND(SUM(purchase_amount), 0) AS tota_revenue
FROM sales
GROUP BY 1;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
	item_purchased,
	ROUND(100.0 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) , 2)AS purchase_percentage
FROM sales
GROUP BY 1
ORDER BY purchase_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
WITH CTE AS(
	SELECT 
		customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segments
	FROM sales
)
SELECT 
	customer_segments, 
	COUNT(*) AS no_of_customers
FROM CTE
GROUP BY 1;

--Q8. What are the top 3 most purchased products within each category?
WITH CTE AS(
	SELECT
		item_purchased,
		category,
		COUNT(*) AS total_purchase_count,
		ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
 	FROM sales
	GROUP BY 2, 1
)
SELECT * FROM CTE
WHERE rank <= 3
ORDER BY category, total_purchase_count DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
	subscription_status,
	COUNT(customer_id) AS repeated_buyers
FROM sales
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
	age_group,
	SUM(purchase_amount) AS total_revenue
FROM sales
GROUP BY 1
ORDER BY 2 DESC;